# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PVHM6R8IkhFLz02N4Ypr8cISKXUM6yC4
"""

import matplotlib.pyplot as plt 
plt.figure(figsize=(10,6))

meses = ["Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro - Incompleto"]
casos = [3195,34632,73449,54406,41861,29106,14957,14018,14023,2067]
titulo = "Casos no Estado do Pará - COVID-19: 2020"
legend = ["Meses - a contar de Março"]

plt.title(titulo)
#plt.barh(meses,casos)
plt.plot(casos, marker = 'o')
plt.xlabel(meses)
plt.ylabel('Fonte: https://www.covid-19.pa.gov.br/#/')
plt.legend(legend)
plt.show()